Name: Compile GMpro Deauther Fixed Library

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spacehuhn Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install Library from Repo Zip
        run: |
          # Membuat folder library manual
          mkdir -p /home/runner/Arduino/libraries
          
          # Mengambil library SimpleCLI
          arduino-cli lib install "SimpleCLI"
          
          # Unzip ArduinoJson versi spesifik yang ada di repo kamu
          unzip -o ArduinoJson-5.13.5.zip -d /home/runner/Arduino/libraries/
          
          # List library untuk memastikan file ada
          ls -R /home/runner/Arduino/libraries/

      - name: Compile GMpro Firmware
        run: |
          # Mengarahkan langsung ke folder tempat file .ino berada
          # Arduino CLI akan otomatis mencari file .ino yang namanya sama dengan foldernya
          arduino-cli compile --fqbn deauther:esp8266:generic:eesz=4M2M \
          ./esp8266_deauther --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro-Deauther-Binary
          path: ./build/*.bin
